### PR TITLE
Issue #5937 - improved VM icon selector UX

### PR DESCRIPTION
**Pull request by js-john**
Solved "Add a tooltip when selecting an OS icon for the selected VM?" #5937

macOS
Screenshot_2023-12-13 13 35 19_UTS18j

Removed extra icon picker pop over for iOS / iPadOS 

iPadOS
Screenshot_2023-12-13 13 34 43_VmeLQ3

iOS
Screenshot_2023-12-13 13 35 40_SqnhUH

### CODE REVIEW

**Comment by rxhfcy** [comment]
Small UI regression:

In UTM 4.5.1 (96), clicking the VM icon itself used to open the "icon picker".
In 4.5.2 (97) however, clicking the VM icon now does nothing, only the new button works

Suggestion: why not make clicking the icon still work as earlier? Feels pretty obvious that if someone clicks the icon, showing the "picker" wouldn't be a surprise. Doing nothing would just be a bit pedantic I think :)

**Comment by osy** [comment]
Feel free to open a new issue with your suggestion as this PR has already been closed.

**Comment by rxhfcy** [comment]
> Feel free to open a new issue with your suggestion as this PR has already been closed.

OK thanks, I opened new issue #6316

**Comment by rxhfcy** [comment]
Also see #6317 for UI wonkiness if the OS name doesn't fit on one line in the icon picker

**Pull request merged**
