### PR TITLE
Add URL Scheme `UTM://` Support

### PR DESCRIPTION
**Pull request by ty-yqs**
https://user-images.githubusercontent.com/61855011/119230349-5ef6ae00-bb4e-11eb-8c6e-c9870dec20a6.MP4

### CODE REVIEW

**Comment by osy** [comment]
What is the use case for this?

**Comment by ty-yqs** [comment]
There are many use cases for this. It can help users open UTM app, download profiles, download `.utm` files and so on. We can add more use cases for it in the future.

**Comment by conath** [comment]
I'd be very interested in adding useful URL-scheme features. [I previously suggested some of them](https://github.com/utmapp/UTM/issues/2280#issuecomment-766096309).

Just opening the app with a URL scheme and no further features is obviously not useful. @osy what do you think about the URL scheme features? Should I try to make it happen?

**Comment by ty-yqs** [comment]
> I'd be very interested in adding useful URL-scheme features. [I previously suggested some of them](https://github.com/utmapp/UTM/issues/2280#issuecomment-766096309).
> 
> Just opening the app with a URL scheme and no further features is obviously not useful. @osy what do you think about the URL scheme features? Should I try to make it happen?

I am very busy these days. If you want to make it happen, you can ask me to make this pull request ready for preview and create a new pull request to add features.

**Comment by conath** [comment]
Superseded by #2670

**Pull request closed without merging**
