### PR TITLE
Fix incomplete parameters

### PR DESCRIPTION
**Pull request by js-john**
1. Fix incomplete parameters for cpu setting.
2. Fix translate error "z系统" to "系统"
3. perform a network requrest in order to show up the alert of "allow network usage"

### CODE REVIEW

**Comment by osy86** [comment]
Why is “sockets=1” needed? What error does this fix?

**Comment by js-john** [comment]
> Why is “sockets=1” needed? What error does this fix?

I tried if the cpu setting in "Architecture" page is more than 2 cores, the setting will not take effect. If the parameter "socket = 1" is included, you can set more than 2 cores. Check it in the task manager.

**Comment by osy86** [comment]
I can not reproduce the “allow network usage" alert. How do you get it to show up? Does setting https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads?language=objc do anything?

**Comment by js-john** [comment]
> I can not reproduce the “allow network usage" alert. How do you get it to show up? Does setting https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads?language=objc do anything?

I am not sure whether the "Allows arbitrary loads" still works...

To reproduce the “allow network usage" alert:
Change a new bundle identifier, build,  and run UTM in your iPhone. When you performing a network request (not in the VMs) the "Allow UTM to use wireless data?" alert will show up.

If this alert did not shown, UTM will not have network usage permission. I tried on my phone, even if DNS is configured correctly, I can't access the network in Internet Explorer and the "Allow UTM to use wireless data?" alert did not show up...

I think it is necessary to add network request codes somewhere in the project...

network

**Comment by osy86** [comment]
Are you sure that is from iOS and not some jailbreak tweak? I can't reproduce it on my phone.

**Comment by js-john** [comment]
> Are you sure that is from iOS and not some jailbreak tweak? I can't reproduce it on my phone.

I'm sure this is from iOS. Since maybe iOS 12? or 13. My phone is never jailbroken.

**Comment by js-john** [comment]
> Are you sure that is from iOS and not some jailbreak tweak? I can't reproduce it on my phone.

I am using iOS13.3.1, all apps have to get network access through this alert

**Comment by saagarjha** [comment]
A China thing, I belive.

**Comment by js-john** [comment]
Ok, I see.

**Comment by osy86** [comment]
That makes sense, I think I want the way ish does it because it looks cleaner and I think the Apple url is smaller in data usage.

**Comment by js-john** [comment]
Thank you!

**Comment by osy86** [comment]
Merged https://github.com/utmapp/UTM/commit/6d3f7d049f7a20282065c0a7f2608db7acb70140 https://github.com/utmapp/UTM/commit/c475ad7975676f24675f71ff780487260b83a145

**Pull request closed without merging**
