### PR TITLE
Update and fix Spanish (Latin America) localization

### PR DESCRIPTION
**Pull request by JezerM**
There were some issues with the last PR, which removed a lot of translations and I didn't notice it. This would be solved in this PR.

Also, added missing translations according to Japanese localization. And, finally added iOS settings translations.

### CODE REVIEW

**Comment by JezerM** [comment]
Also, added spanish localization of README at `README.es.md`.

**Comment by JezerM** [comment]
I'll update this PR with the latest changes soon~

**Comment by JezerM** [comment]
Well, I guess I will create another PR xd

**Comment by osy** [comment]
@JezerM sorry I did not see that message

**Comment by JezerM** [comment]
No problem~

**Pull request merged**
