### PR TITLE
Allow import UTM from not .utm.zip

### PR DESCRIPTION
**Pull request by smattar2020**
Sometimes UTM has problems importing VMs that are actually .utm.zip's but their URL doesn't show that. This attempts to fix that.

### CODE REVIEW

**Comment by conath** [comment]
Can you make a branch with only the first commit? [ff9326e](https://github.com/utmapp/UTM/pull/3954/commits/ff9326ef7fa9386abe30d1867785ebe1e40cb4b0) 

The other changes don't belong to this issue.

**Comment by smattar2020** [comment]
How do I do that?

**Comment by conath** [comment]
Create a new branch in your fork (`git checkout -b dev-fix-download-url`), then reset it to two commits earlier (`git reset HEAD~2 --hard`) and push that branch (`git push --set-upstream origin dev-fix-download-url`). Then make a new PR.

**Comment by smattar2020** [comment]
Thank you

**Comment by smattar2020** [comment]
It still says no differences

**Comment by conath** [comment]
Huh... if you were on master branch and did the above commands, it should have worked. Just tried the commands myself.

**Comment by smattar2020** [comment]
It is erroring out now
`fatal: ambiguous argument 'HEAD~2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'`

**Comment by conath** [comment]
What does your `git status` say?

**Comment by smattar2020** [comment]
Oops! I was on a different repo. Now it works. Thank you.

**Pull request closed without merging**
