### PR TITLE
aarch64 fixes:

### PR DESCRIPTION
**Pull request by ledwardchow**
* launch qemu with -machine virt
* remove qxl
* fixed dylib filename generation

### CODE REVIEW

**Comment by ledwardchow** [comment]
fixes #34

**Comment by osy86** [comment]
Does `virtio-gpu-pci` actually work? I don’t think it’s actually supported. Would be better to just drop the vga option and use the default.

**Comment by pixelomer** [comment]
This also fixed PowerPC for me.

**Comment by Atemu** [comment]
@ledwardchow why was qxl disabled?

Is the reason still relevant with modern versions of qemu?

**Pull request merged**
