### PR TITLE
Graphics card argument configurable

### PR DESCRIPTION
**Pull request by js-john**
Make the -device graphics card argument configurable in the display config page 
#303

### CODE REVIEW

**Comment by Ryanchen48210** [comment]
Nice, I watched your video about the virtual GPU for win10, and it performed very well.

**Comment by cheny0y0** [comment]
Section?

**Comment by osy** [comment]
Thanks but the constants should be generated like the other ones. Look at the sound cards and network cards as examples.

**Comment by js-john** [comment]
> Thanks but the constants should be generated like the other ones. Look at the sound cards and network cards as examples.

ok, I see

**Comment by osy** [comment]
`UTMConfiguration+ConstantsGenerated.m` should NOT be manually edited as stated in the header... It is generated by the `scripts/const-gen.py` script. Don't worry, I can modify it but it'll have to be the next release.

**Comment by js-john** [comment]
> `UTMConfiguration+ConstantsGenerated.m` should NOT be manually edited as stated in the header... It is generated by the `scripts/const-gen.py` script. Don't worry, I can modify it but it'll have to be the next release.

Sorry..I didn't notice that..
Should I close this PR?

**Comment by osy** [comment]
No I’ll take over it.

**Comment by osy** [comment]
@js-john I cannot find qxl-vga in qemu:

```
$ qemu-system-x86_64 -vga none -device qxl-vga
qemu-system-x86_64: -device qxl-vga: 'qxl-vga' is not a valid device model name
$ qemu-system-x86_64 -vga none -device qxl    
qemu-system-x86_64: -device qxl: 'qxl' is not a valid device model name
```

**Review by cheny0y0 — COMMENTED** [review]
Large diffs are not rendered. DX

**Pull request merged**
