### PR TITLE
input: implemented gamepad simulation keyboard and mouse.

### PR DESCRIPTION
**Pull request by js-john**
I deleted the branch so the last pull request can not be opened again..😅

### CODE REVIEW

**Comment by js-john** [comment]
Screenshot_2020-04-03 19 05 20_lXDLtC

I did added the XCODE_PATH in Secrets setting..

**Comment by osy86** [comment]
I'm going to push this off until a future release due to the amount of other changes that is making into 0.9.

**Comment by osy86** [comment]
@js-john can you grant me write permissions to your fork?

**Comment by js-john** [comment]
Yes！

**Pull request merged**
