### PR TITLE
readme.Japanese.md

### PR DESCRIPTION
**Pull request by XJ-boy**
readme.md-Japanese

### CODE REVIEW

**Comment by osy86** [comment]
1. Please use the name `README.Japanese.md`
2. Only include the translation in the file.

**Comment by hui2007** [comment]
I think the language file should be like the form of “en-us”, for example ,the English has “American English” and ”British English”, the Chinese has “Simplified Chinese” and “Traditional Chinese”. If it only use the form "English",”Chinese”, people can't distinguish them well.

**Comment by osy86** [comment]
That's true. Let's use https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html

`[language designator]` or `[language designator]-[script designator]` depending on the language.

**Comment by osy86** [comment]
I had to revert the merge after finding many typos and bad formatting errors. I should have checked before clicking merge, sorry. Feel free to re-submit once all the errors are fixed, and the comments from https://github.com/utmapp/UTM/pull/350#issuecomment-634219872 are taken care of.

**Pull request merged**
