### PR TITLE
Added README in Japanese

### PR DESCRIPTION
**Pull request by MTS-Rabbit**

### CODE REVIEW

**Comment by osy** [comment]
@cs-sugar Did you translate this yourself or with an automated tool?

**Comment by cs-sugar** [comment]
I have used all of them. If I find that the translation of automation software is improper, I will revise it myself. I hope you can agree.

**Comment by kkk669** [comment]
Great work, but this translation feels very unnatural and misleading in some parts. I'm a native Japanese speaker.

**Comment by cs-sugar** [comment]
> Great work, but this translation feels very unnatural and misleading in some parts. I'm a native Japanese speaker.

OK, you can correct some inappropriate places.

**Comment by akihikodaki** [comment]
I think you have to state what tool you used at least. Otherwise others cannot see if the license of the translation and one of this project is consistent.

**Comment by js-john** [comment]
> Great work, but this translation feels very unnatural and misleading in some parts. I'm a native Japanese speaker.

I'm learning Japanese and I am going to work in Tokyo this year. I want to translate UTM into Japanese as a practice, but I'm not confidence about my Japanese level 😂. Can you help me with the translation?
I want to send you the translated UTM ipa file to you. Would you like to check the mistakes for me?

私は今日本語を勉強しています、今年は仕事で東京に行きます。私はUTMを日本語に翻訳するつもりです、しかし、自分の日本語レベルは自信がないです。

**Comment by akihikodaki** [comment]
An IPA file is helpful, but it is also nice if you share the source code. I suggest to open a draft pull request so others can see the code. I'll review once you have a pull request. (I'm a native Japanese speaker.)

**Comment by js-john** [comment]
> An IPA file is helpful, but it is also nice if you share the source code. I suggest to open a draft pull request so others can see the code. I'll review once you have a pull request. (I'm a native Japanese speaker.)

Sure, I will open a pull request tomorrow. (shame for my poor Japanese level)

**Pull request closed without merging**
